sudo: true
dist: trusty
language:
  - generic
cache:
  - apt

env:
  - CI_SOURCE_PATH=$(pwd)

# Install package dependencies
before_install:
  # Testing $DISPLAY
  - echo $DISPLAY

  # Install OpenRAVE
  - mkdir -p ~/git; cd ~/git
  - git clone https://github.com/crigroup/openrave-installation.git
  - cd openrave-installation
  - ./install-dependencies.sh
  - ./install-fcl.sh
  - ./install-openrave.sh
  - sudo apt install python-tk
  - pip install --ignore-installed cython matplotlib coverage python-coveralls cvxopt --user

install:
  # Install dependencies
  - mkdir -p ~/git/ && cd ~/git/
  - git clone https://github.com/hungpham2511/qpOASES
  - cd qpOASES/ && mkdir bin && make
  - cd interfaces/python/
  - python setup.py install --user

script:
  - cd $CI_SOURCE_PATH
  - pip install -r requirements.txt --user
  - python setup.py develop --user  # need to run the develop command to have coverage working. install command (below) should work just fine.
  # - python setup.py install --user
  - py.test --cov=toppra tests -Wonce

after_success:
  - coveralls
